# Project information
site_name: D3TA-Go Docs

# Repository
repo_name: d3ta-go/docs
repo_url: https://github.com/d3ta-go/docs
edit_uri: https://github.com/d3ta-go/docs/edit/main/en/docs/

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: blue grey
    accent: blue grey

# Navigation
nav:
  - Home: index.md
  - DDD Reference:
      - Overview: ddd-reference/overview.md
      - I. Putting the Model to Work: ddd-reference/01-putting-the-model-to-work.md
      - II. Building Blocks of a Model-Driven Design:
          - Overview: ddd-reference/02-building-blocks-of-a-model-driven-design.md
          - Layered Architecture:
              - Overview: ddd-reference/layered-architecture/overview.md
      - III. Supple Design: ddd-reference/03-supple-design.md
